#!/usr/bin/env bash
name="py3-cython"
version="0.29.34"
description="A Python to C compiler."
depends="python3.11,libxml2,libxslt"
group="dev.python"
source=("https://github.com/cython/cython/archive/refs/tags/$version.tar.gz")

  
setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
  python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

