#!/usr/bin/env bash
name="py3-validate"
version="1.0.1"
description="Python module for GNU parted"
source="https://files.pythonhosted.org/packages/02/f8/97105237d0ba693b6f0bdcd94da0504e9a4433988c4393d8d3049094be7a/validate-1.0.1.tar.gz"
depends="parted,python"
builddepend="py3-wheel,py3-installer,py3-build"
group="dev.python"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
	python3 -m build -wn
}

package(){
	cd $SOURCEDIR
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

