#!/usr/bin/env bash
name="py3-base"
version="1.0.0"
description="py3 font aliases "
source=""
depends="asciidoc,graphviz,py3-babel,py3-build,py3-cairo,py3-cerberus,py3-cffi,py3-cparser,py3-curl, \
py3-cython,py3-dbus,py3-distro,py3-distutils-extra,py3-docutils,py3-editables,py3-feedgen, \
py3-flit,py3-hatchling,py3-hotdoc,py3-imagesize,py3-inotify,py3-installer,py3-jinja,py3-libxdo, \
py3-lxml,py3-mako,py3-markdown,py3-markupsafe,py3-multiprocess,py3-packaging,py3-pam,py3-parsing,  \
py3-pathspec,py3-pdm-pep517,py3-pexpect,py3-pillow,py3-pip,py3-psutil,py3-ptyprocess, \
py3-pygments,py3-pygobject,py3-pyproject-hooks,py3-requests,py3-setproctitle,py3-setuptools,\
py3-setuptools-scm,py3-six,py3-snowballstemmer,py3-sphinx,py3-tinycss2,py3-tomli,py3-tomli-w, \
py3-typogrify,py3-tz,py3-webencodings,py3-wheel,py3-xapp,py3-yaml,smartypants"
group="media.fonts"

setup(){
	echo ""
}

build(){
   echo ""
}

package(){
mkdir -p $DESTDIR/tmp
touch $DESTDIR/tmp/py3-base
 
}

