#!/usr/bin/env bash
name="py3-build"
release="2"
version="1.2.1"
url="https://github.com/pypa/build/"
description="Easily download, build, install, upgrade, and uninstall Python packages"
license="GPLv3"
source="https://github.com/pypa/build/archive/refs/tags/$version.tar.gz"
depends="python,py3-wheel"
builddepend=""
md5sums="d6230170909b380ee0dc1f77f96b3635"
group="dev.python"
arch="x86_64"

setup(){
	echo ""
}

build(){
	echo ""
}

package(){
	cd $SOURCEDIR
    mkdir -p $DESTDIR/usr/lib64/python3/build
    cp -prfv src/build/* $DESTDIR/usr/lib64/python3/build
}

