#!/usr/bin/env bash
name="py3-build"
version="1.2.1"
url="https://github.com/pypa/build"
description="A simple, correct Python build frontend"
source="https://github.com/pypa/build/archive/refs/tags/$version.tar.gz"
depends="python"
group="dev.python"
export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0

setup(){
cd $SOURCEDIR

}

build(){
    echo ""
}

package(){
	mkdir -p $DESTDIR/usr/lib64/python3/build
    cp -prfv src/build/* $DESTDIR/usr/lib64/python3/build

}

