#!/usr/bin/env bash
name="py3-qt5"
version="5.15.10"
description="A set of Python 3 bindings for the Qt toolkit"
source="https://pypi.python.org/packages/source/P/PyQt5/PyQt5-${version}.tar.gz"
depends="python,qt5-base"
builddepend="py3-pyqt-build,py3-opengl,py3-dbus,qt5-connectivity,qt5-multimedia,qt5-tools,qt5-serialport,qt5-speech,qt5-svg,qt5-websockets,qt5-x11extras,qt5-xmlpatterns,qt5-remoteobjects,qt5-quick3d,qt5-sensors,qt5-webchannel,qt5-location"
group="dev.python"

setup () {
	export PATH=/usr/bin/qt5:$PATH
	cd $SOURCEDIR
sip-build \
		--confirm-license \
		--api-dir /usr/share/qt5/qsci/api/python \
		--pep484-pyi \
		--no-make
}

build () {
    make -C build
}

package () {
    make INSTALL_ROOT="$DESTDIR" -C build install
    mkdir -p $DESTDIR/usr/lib64
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
	
    python -m compileall -d / "$DESTDIR"/usr/lib64
	python -O -m compileall -d / "$DESTDIR"/usr/lib64

}

