#!/usr/bin/env bash
name="py3-parsing"
version="3.1.2"
url="https://pypi.org/project/pyparsing/"
description="Python library for creating PEG parsers"
license="GPLv3"
source="https://github.com/pyparsing/pyparsing/releases/download/${version}/pyparsing-${version}.tar.gz"
depends="python"
builddepend=""
md5sums="fadc2f3bf5872bf6310576a86c3566e0"
group="dev.python"
arch="x86_64"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
	python3 -m build --skip-dependency-check
}


package(){
    cd $SOURCEDIR
	python3 -m installer --destdir="$DESTDIR" dist/*.whl

}

