#!/usr/bin/env bash
name="py3-pdm-pep517"
version="1.1.4"
description="A PEP 517 backend for PDM that supports PEP 621 metadata"
depends="py3-tomli-w,python"
group="dev.python"

setup()
{
cp -prfv $PACKAGEDIR/python-pdm-pep517-1.1.2-devendor.patch  $SOURCEDIR/
cd $SOURCEDIR
    patch -Np1 -d pdm-backend-$version -i python-pdm-pep517-1.1.2-devendor.patch

}

build(){
    python -m build --wheel --skip-dependency-check --no-isolation
}

package(){
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

