#!/usr/bin/env bash
name="libusb"
version="1.0.26"
url="https://github.com/libusb/libusb"
description="Userspace access to USB devices "

source="https://github.com/libusb/libusb/archive/refs/tags/v$version.tar.gz"
depends="eudev"
builddepend="libcap-ng"
group="dev.libs"

setup(){
cd $SOURCEDIR
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make DESTDIR=$DESTDIR install $jobs
}

