#!/usr/bin/env bash
name="py3-installer"
version="0.7.0"
url="https://github.com/pypa/installer/"
description="Easily download, build, install, upgrade, and uninstall Python packages"
source="https://github.com/pypa/installer/archive/refs/tags/$version.tar.gz"
depends="python"
group="dev.python"


setup(){
cd $SOURCEDIR

}

build(){
    python3 -m build -wn --skip-dependency-check
}

package(){
	#mkdir -p $DESTDIR/usr/lib64/python3/installer
    #cp -prfv src/installer/* $DESTDIR/usr/lib64/python3/installer
	PYTHONPATH=src python3 -m installer --destdir="$DESTDIR" dist/*.whl

}

