#!/usr/bin/env bash
name="py3-markupsafe"
version="2.1.5"
description="Implements a XML/HTML/XHTML Markup safe string"
source="https://github.com/pallets/markupsafe/archive/refs/tags/${version}.tar.gz"
depends="python"
builddepend="py3-setuptools py3-wheel"
group="dev.python"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}"  --optimize=1
}

