#!/usr/bin/env bash
name="py3-pluggy"
version="1.4.0"
description="Plugin management and hook calling for Python"
source=("https://files.pythonhosted.org/packages/54/c6/43f9d44d92aed815e781ca25ba8c174257e27253a94630d21be8725a2b59/pluggy-1.4.0.tar.gz")
depends="python,py3-pdm-pep517"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --skip-build
}


