#!/usr/bin/env bash
name="py3-tomli-w"
version="1.0.0"
source=("https://github.com/hukkin/tomli-w/archive/refs/tags/${version}.zip")
description="Lil TOML writer"
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
     python3 -m build --wheel --no-isolation
}

package(){
    python3 -m installer --destdir="${DESTDIR}" dist/*.whl
}

