#!/bin/bash
name="make-ca"
version="1.10"
url="https://github.com/lfs-book/make-ca"
description="Ssl certificates"
source="https://github.com/lfs-book/make-ca/releases/download/v1.10/make-ca-${version}.tar.xz"

depends="p11-kit"
group="app.misc"

setup()
{	cd $SOURCEDIR
	cp $PACKAGEDIR/make-ca.sysconf ./
}
build(){
    sed -i "s|/usr/bin/cut|/bin/cut|g" make-ca
    sed -i "s|/usr/bin/md5sum|/bin/md5sum|g" make-ca
    make
}

package(){
    make install DESTDIR=$DESTDIR SBINDIR="/sbin/"
    mkdir -p "$DESTDIR"/etc/sysconf.d
    install make-ca.sysconf "$DESTDIR"/etc/sysconf.d/make-ca
}
