#!/usr/bin/env bash
name="py3-dbus"
#_name="dbus-python"
version="1.3.2"
description="Python3 bindings for DBUS"
source="https://gitlab.freedesktop.org/dbus/dbus-python/-/archive/dbus-python-${version}/dbus-python-dbus-python-${version}.tar.gz"
depends="python"
group="dev.python"

setup(){
    cd $SOURCEDIR
    meson setup $BUILDDIR \
        --prefix=/usr \
        --libdir=/usr/lib64
}
build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
    
	python3 -m compileall -d /usr/lib64 "$DESTDIR/usr/lib64"
	python3 -O -m compileall -d /usr/lib64 "$DESTDIR/usr/lib64"
	
	# Install egg-info
	install -Dm644 -t "$DESTDIR`python3 -c 'import site; print(site.getsitepackages()[0])'`/dbus_python-$version.egg-info/" "$SOURCEDIR"/


}

