#!/usr/bin/env bash
name="py3-dbus"
_name="dbus-python"
version="1.3.2"
source=("https://dbus.freedesktop.org/releases/dbus-python/$_name-${version}.tar.gz")
description="Python3 bindings for DBUS"
depends="python"
group="dev.python"



setup(){
cd $SOURCEDIR
   $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

