#!/usr/bin/env bash
name="py3-pygobject"
version="3.48.2"
url="Python bindings for GObject Introspection"
description="Python bindings for GObject Introspection"
source="https://gitlab.gnome.org/GNOME/pygobject/-/archive/$version/pygobject-$version.tar.gz"
depends="python$pyver,gobject-introspection"
builddepend=""
group="dev.python"
arch="x86_64"

setup(){
    cd $SOURCEDIR
    meson setup $BUILDDIR \
        --prefix=/usr \
        --libdir=/usr/lib \
        -Db_lto=true \
        -Ddefault_library=both
}
build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}
