#!/usr/bin/env bash
name="py3-pygobject"
version="3.43.1"
url="Python bindings for GObject Introspection"
description="Python bindings for GObject Introspection"
license="GPLv3"
source="https://gitlab.gnome.org/GNOME/pygobject/-/archive/$version/pygobject-$version.tar.gz"
pyver=$(python3 -c "import sys; print(str( sys.version_info[0]) +\".\"+ str(sys.version_info[1] ))")
depends="python$pyver,gobject-introspection"
builddepend=""
md5sums="644705774d5cd6b668e95ac33ba64de2"
group="dev.python"
arch="x86_64"

setup(){
	cd $SOURCEDIR
}

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
