#!/usr/bin/env bash
name="smartypants"
version="2.0.1"
source=("https://github.com/leohemsted/smartypants.py/archive/refs/tags/v$version.tar.gz")
description="ASCII quote-dot-dash to HTML entity converter"
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
