#!/usr/bin/env bash
name="pcre"
version="8.45"
url="https://www.pcre.org"
description="Perl-compatible regular expression library"
source="https://downloads.sourceforge.net/project/pcre/pcre/${version}/pcre-${version}.tar.bz2"
depends="readline,zlib,bzip2"
group="dev.libs"

setup () {
    $SOURCEDIR/configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--enable-unicode-properties \
		--enable-pcre16 \
		--enable-pcre32 \
		--enable-jit \
		--enable-pcregrep-libz \
		--enable-pcregrep-libbz2 \
		--enable-pcretest-libreadline

}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

