#!/usr/bin/env bash
name="py3-xapp"
version="2.4.0"
source=("https://github.com/linuxmint/python3-xapp/archive/refs/tags/${version}.tar.gz")
description="Python Xapp Library"
depends="python,py3-psutil"
group="dev.python"



setup(){
cd $SOURCEDIR
    meson $BUILDDIR ./ \
        --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    meson compile -C $BUILDDIR
}

package(){
    meson install -C $BUILDDIR --destdir=${DESTDIR}
    python3 -m compileall -d / "$DESTDIR"/usr/lib
    python3 -O -m compileall -d / "$DESTDIR"/usr/lib
}

