#!/usr/bin/env bash
name="py3-babel"
version="2.12.1"
description="Python3 i18n tool"
depends="python"
group="dev.python"

source=("https://github.com/python-babel/babel/archive/refs/tags/v${version}.tar.gz")
setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


