#!/usr/bin/env bash
name="py3-pycups"
version="2.0.1"
description="Python bindings for cups"
source="https://github.com/OpenPrinting/pycups/archive/refs/tags/v$version.tar.gz"
depends="python,cups"
builddepend="py3-setuptools"
group="dev.python"

setup(){
	echo ""
}

build () {
	cd $SOURCEDIR
    python3 setup.py build
}

package () {
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}

