#!/usr/bin/env bash
name="tar"
version="1.35"
description="Utility used to store, backup, and transport files"
source="https://ftp.gnu.org/gnu/tar/tar-$version.tar.xz"
depends="glibc,readline,ncurses"
groups="app.arch"
setup()
{
	cd $SOURCEDIR
	#export CFLAGS="$CFLAGS -flto=auto"
	export FORCE_UNSAFE_CONFIGURE=1
	./configure --prefix=/usr \
		--sbindir=/usr/bin \
		--libexecdir=/usr/lib/tar \
		--enable-backup-scripts

	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


