#!/usr/bin/env bash
name="pixman"
version="0.43.4"
description="Low-level pixel manipulation routines"
source="https://www.x.org/archive/individual/lib/pixman-$version.tar.gz"
depends=""
builddepend="libpng,meson"
group="x11.libs"

setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddefault_library=both \
        -Dloongson-mmi=disabled \
		-Dvmx=disabled \
		-Darm-simd=disabled \
		-Dneon=disabled \
		-Da64-neon=disabled \
		-Diwmmxt=disabled \
		-Dmips-dspr2=disabled \
		-Dgtk=disabled

}

build(){
    ninja -C $BUILDDIR
}

package(){
    ninja -C $BUILDDIR install
}

