#!/usr/bin/env bash
version="master"
name="live-installer"
depends="glibc,py3-defusedxml,py3-parted"
description="iso yükleme  apps"
source="https://github.com/basitdagitim/live-installer/archive/refs/heads/master.zip"
groups="app.editor"
setup()
{
	cd $SOURCEDIR
	./configure --prefix=/usr
	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR

}


