#!/usr/bin/env bash
version="2.0.4"
name="live-installer"
depends="glibc,py3-defusedxml,py3-parted"
description="şıkıştırma kütüphanesi"
source="https://github.com/pardus/pardus-installer/archive/refs/tags/current.tar.gz"
groups="app.editor"
setup()
{
	cd $SOURCEDIR
	./configure --prefix=/usr
	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR

}


