#!/usr/bin/env bash
name="py3-lxml"
version="4.9.2"
source=("https://github.com/lxml/lxml/archive/refs/tags/lxml-$version.tar.gz")
description="Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API."
depends="python3.11,libxml2,libxslt,py3-cython"
group="dev.python"

setup()
{
cd $SOURCEDIR
}

build(){
    python3 setup.py build
}

package(){
 python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

