#!/usr/bin/env bash
version="3.7.2"
name="libarchive"
depends="glibc,openssl"
description="şıkıştırma kütüphanesi"
source="https://www.libarchive.org/downloads/${name}-${version}.tar.xz"
groups="app.arch"
setup()
{
	cd $SOURCEDIR
	./configure --prefix=/usr
	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


