#!/usr/bin/env bash
name="py3-certifi"
version="2024.6.2"
source="https://files.pythonhosted.org/packages/07/b3/e02f4f397c81077ffc52a538e0aec464016f1860c472ed33bd2a1d220cc5/certifi-2024.6.2.tar.gz"
description="A Python interface to the PAM library"
depends="python"

group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 -m build --wheel --no-isolation
}

package(){
	python3 -m installer --destdir="${DESTDIR}" dist/*.whl
	
	mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}


