#!/bin/sh

if [ ! -f /etc/shadow ] ; then
    echo "root:*::0:::::" > /etc/shadow
    chmod 600 /etc/shadow
    chown root /etc/shadow
    chgrp root /etc/shadow
    else
    chmod 600 /etc/shadow
    chown root /etc/shadow
    chgrp root /etc/shadow
fi

if [ ! -f /etc/group ] ; then
    touch /etc/group
    chmod 600 /etc/group
    chown root /etc/group
    chgrp root /etc/group
    else
    chmod 600 /etc/group
    chown root /etc/group
    chgrp root /etc/group
fi
mv /bin/su /bin/su-old
